fix: modify jobs to use reusable action for issues
sigstore/root-signing pull request #864
Opened 2023-06-27 08:06 UTC by yrobla

Closes: #848 

#### Summary

Before it was set up to use a reusable workflow,
but we need to call it from inside the jobs. So it was converted to a composite action
#### Release Note

NONE

#### Documentation

No documentation needed as it is a change for CI

2023-06-27 15:19 UTC, haydentherapper approved these changes, later dismissed

2023-06-27 15:44 UTC, asraa requested changes

2023-06-27 15:44 UTC, asraa commented on .github/workflows/reuseable-snapshot-timestamp.yml
> +        uses: sigstore/sigstore-probers/.github/actions/create-issue.yml@main
hmm i'm not sure this is the correct syntax for referring to an action - I don't think it should require a `.yml`, this would indicate that its a reusable workflow.

It should look something like `sigstore/sigstore-probers/.github/actions/create-issue@main` where the `create-issue` directory contains an `action.yml`.

You might want to test this action first in your own fork.

2023-06-28 06:34 UTC, yrobla commented on .github/workflows/reuseable-snapshot-timestamp.yml
> +        uses: sigstore/sigstore-probers/.github/actions/create-issue.yml@main
i actually was testing with act, didn't give me any error. But i believe it wasn't even arriving at the point to trigger this job

2023-06-28 06:45 UTC, yrobla commented on .github/workflows/reuseable-snapshot-timestamp.yml
> +        uses: sigstore/sigstore-probers/.github/actions/create-issue.yml@main
I needed to modify the structure for the reusable action here: 
https://github.com/sigstore/sigstore-probers/pull/79

2023-06-28 13:50 UTC, asraa commented on .github/workflows/reuseable-snapshot-timestamp.yml
> +        uses: sigstore/sigstore-probers/.github/actions/create-issue.yml@main
nice! looks right now

2023-06-28 13:51 UTC, asraa approved these changes

2023-06-28 19:40 UTC, haydentherapper approved these changes

2023-06-28 19:40 UTC, merged

2023-06-29 00:42 UTC, haydentherapper commented
Looks like there are some permissions we need to update. See https://github.com/sigstore/root-signing/actions/runs/5407004739/jobs/9824508976, there was a failure but no issue filed.

2023-06-29 14:34 UTC, haydentherapper commented
@yrobla Looks like there's a different issue, it can't find the script - https://github.com/sigstore/root-signing/actions/runs/5413400384/jobs/9838909164

2023-06-29 14:42 UTC, yrobla commented
> @yrobla Looks like there's a different issue, it can't find the script - https://github.com/sigstore/root-signing/actions/runs/5413400384/jobs/9838909164

indeed, i checked and the problem is that really reusable actions are not designed to work like that. It tries to find the script in the local checked repo instead of on the remote one. I think that the best take here is to move the bash code to the action itself... i will work on that

2023-06-29 14:44 UTC, haydentherapper commented
Thank you for investigating!