config: preprod to prod syncs are no longer automated
sigstore/root-signing pull request #912
Opened 2023-08-07 16:28 UTC by hectorj2f

#### Summary

The `preprod-to-prod` syncs is no longer automated, we only support a manual trigger.

This issue is related to https://github.com/sigstore/root-signing/issues/893.

#### Release Note

preprod-to-prod syncs are no longer automated, only supporting a manual trigger.

#### Documentation

2023-08-07 16:40 UTC, lkatalin approved these changes

2023-08-07 20:32 UTC, haydentherapper commented
/hold until we've planned out the needed changes, I want to make sure we still have syncs from preprod til we stop using the bucket

2023-08-07 20:32 UTC, haydentherapper requested changes
/hold

2023-08-08 09:17 UTC, hectorj2f commented
@haydentherapper Let me know! When we can merge it.

2023-08-18 21:42 UTC, haydentherapper commented on .github/workflows/sync-preprod-to-prod.yml
>        trigger_sync:
Given this is manual now, we should remove the trigger_sync input too, and remove the "check sync conditions" step

2023-08-18 22:40 UTC, haydentherapper commented
Will merge after https://github.com/sigstore/root-signing/pull/916

2023-08-21 16:26 UTC, haydentherapper approved these changes

2023-08-21 17:16 UTC, haydentherapper commented
Closing in favor of https://github.com/sigstore/root-signing/pull/928

2023-08-21 17:16 UTC, closed without merging